CREATE TABLE auth_audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    username VARCHAR(255),
    event_type VARCHAR(64) NOT NULL,
    success BOOLEAN NOT NULL,
    ip VARCHAR(64),
    user_agent TEXT,
    session_id VARCHAR(64),
    details TEXT
);
