DO $$
BEGIN
    IF to_regclass('public.cohorts') IS NOT NULL
        AND EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_name = 'cohorts'
              AND column_name IN ('max_students', 'current_students', 'semester_id', 'class_id')
        )
    THEN
        IF to_regclass('public.cohorts_legacy') IS NULL THEN
            EXECUTE 'ALTER TABLE cohorts RENAME TO cohorts_legacy';
        ELSE
            EXECUTE 'ALTER TABLE cohorts RENAME TO cohorts_legacy_2';
        END IF;

        IF to_regclass('public.cohorts_id_seq') IS NOT NULL THEN
            IF to_regclass('public.cohorts_legacy_id_seq') IS NULL THEN
                EXECUTE 'ALTER SEQUENCE cohorts_id_seq RENAME TO cohorts_legacy_id_seq';
                EXECUTE 'ALTER TABLE cohorts_legacy ALTER COLUMN id SET DEFAULT nextval(''cohorts_legacy_id_seq'')';
            ELSIF to_regclass('public.cohorts_legacy_2_id_seq') IS NULL AND to_regclass('public.cohorts_legacy_2') IS NOT NULL THEN
                EXECUTE 'ALTER SEQUENCE cohorts_id_seq RENAME TO cohorts_legacy_2_id_seq';
                EXECUTE 'ALTER TABLE cohorts_legacy_2 ALTER COLUMN id SET DEFAULT nextval(''cohorts_legacy_2_id_seq'')';
            END IF;
        END IF;
    END IF;

    IF to_regclass('public.cohorts') IS NULL THEN
        EXECUTE '
            CREATE TABLE cohorts (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                code VARCHAR(50) NOT NULL UNIQUE,
                name VARCHAR(255) NOT NULL,
                start_year INT NOT NULL,
                end_year INT NOT NULL,
                active BOOLEAN NOT NULL DEFAULT TRUE
            )
        ';
        EXECUTE 'CREATE TRIGGER trg_update_cohorts_updated_at BEFORE UPDATE ON cohorts FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()';
    ELSE
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name = 'cohorts' AND column_name = 'start_year'
        ) THEN
            EXECUTE 'ALTER TABLE cohorts ADD COLUMN start_year INT';
        END IF;

        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name = 'cohorts' AND column_name = 'end_year'
        ) THEN
            EXECUTE 'ALTER TABLE cohorts ADD COLUMN end_year INT';
        END IF;

        EXECUTE '
            UPDATE cohorts
            SET start_year = COALESCE(start_year, EXTRACT(YEAR FROM CURRENT_DATE)::INT)
            WHERE start_year IS NULL
        ';

        EXECUTE '
            UPDATE cohorts
            SET end_year = COALESCE(end_year, start_year + 4)
            WHERE end_year IS NULL
        ';

        EXECUTE 'ALTER TABLE cohorts ALTER COLUMN start_year SET NOT NULL';
        EXECUTE 'ALTER TABLE cohorts ALTER COLUMN end_year SET NOT NULL';
    END IF;
END $$;

