INSERT INTO permissions (name, resource, action, description, created_at, updated_at) VALUES
  ('DEPARTMENT:CREATE', 'DEPARTMENT', 'CREATE', 'Create department', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('DEPARTMENT:READ', 'DEPARTMENT', 'READ', 'Read department', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('DEPARTMENT:UPDATE', 'DEPARTMENT', 'UPDATE', 'Update department', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('DEPARTMENT:DELETE', 'DEPARTMENT', 'DELETE', 'Delete department', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('CLASS:CREATE', 'CLASS', 'CREATE', 'Create class', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('CLASS:READ', 'CLASS', 'READ', 'Read class', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('CLASS:UPDATE', 'CLASS', 'UPDATE', 'Update class', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('CLASS:DELETE', 'CLASS', 'DELETE', 'Delete class', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('SUBJECT:CREATE', 'SUBJECT', 'CREATE', 'Create subject', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('SUBJECT:READ', 'SUBJECT', 'READ', 'Read subject', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('SUBJECT:UPDATE', 'SUBJECT', 'UPDATE', 'Update subject', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('SUBJECT:DELETE', 'SUBJECT', 'DELETE', 'Delete subject', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('SEMESTER:CREATE', 'SEMESTER', 'CREATE', 'Create semester', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('SEMESTER:READ', 'SEMESTER', 'READ', 'Read semester', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('SEMESTER:UPDATE', 'SEMESTER', 'UPDATE', 'Update semester', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('SEMESTER:DELETE', 'SEMESTER', 'DELETE', 'Delete semester', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('COHORT:CREATE', 'COHORT', 'CREATE', 'Create cohort', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('COHORT:READ', 'COHORT', 'READ', 'Read cohort', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('COHORT:UPDATE', 'COHORT', 'UPDATE', 'Update cohort', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('COHORT:DELETE', 'COHORT', 'DELETE', 'Delete cohort', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('SECTION:CREATE', 'SECTION', 'CREATE', 'Create section', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('SECTION:READ', 'SECTION', 'READ', 'Read section', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('SECTION:UPDATE', 'SECTION', 'UPDATE', 'Update section', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('SECTION:DELETE', 'SECTION', 'DELETE', 'Delete section', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('TEACHER:CREATE', 'TEACHER', 'CREATE', 'Create teacher', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('TEACHER:READ', 'TEACHER', 'READ', 'Read teacher', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('TEACHER:UPDATE', 'TEACHER', 'UPDATE', 'Update teacher', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('TEACHER:DELETE', 'TEACHER', 'DELETE', 'Delete teacher', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('STUDENT:CREATE', 'STUDENT', 'CREATE', 'Create student', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('STUDENT:READ', 'STUDENT', 'READ', 'Read student', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('STUDENT:UPDATE', 'STUDENT', 'UPDATE', 'Update student', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('STUDENT:DELETE', 'STUDENT', 'DELETE', 'Delete student', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('STUDENT_CLASS:CREATE', 'STUDENT_CLASS', 'CREATE', 'Create student class', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('STUDENT_CLASS:READ', 'STUDENT_CLASS', 'READ', 'Read student class', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('STUDENT_CLASS:UPDATE', 'STUDENT_CLASS', 'UPDATE', 'Update student class', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('STUDENT_CLASS:DELETE', 'STUDENT_CLASS', 'DELETE', 'Delete student class', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (name) DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.name LIKE 'DEPARTMENT:%'
WHERE r.name = 'ROLE_ADMIN'
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.name LIKE 'CLASS:%'
WHERE r.name = 'ROLE_ADMIN'
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.name LIKE 'SUBJECT:%'
WHERE r.name = 'ROLE_ADMIN'
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.name LIKE 'SEMESTER:%'
WHERE r.name = 'ROLE_ADMIN'
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.name LIKE 'COHORT:%'
WHERE r.name = 'ROLE_ADMIN'
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.name LIKE 'SECTION:%'
WHERE r.name = 'ROLE_ADMIN'
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.name LIKE 'TEACHER:%'
WHERE r.name = 'ROLE_ADMIN'
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.name LIKE 'STUDENT:%'
WHERE r.name = 'ROLE_ADMIN'
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.name LIKE 'STUDENT_CLASS:%'
WHERE r.name = 'ROLE_ADMIN'
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.name IN (
  'DEPARTMENT:READ',
  'CLASS:READ',
  'SUBJECT:READ',
  'SEMESTER:READ',
  'COHORT:READ',
  'SECTION:READ',
  'STUDENT_CLASS:READ',
  'TEACHER:READ'
)
WHERE r.name = 'ROLE_TEACHER'
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.name IN (
  'DEPARTMENT:READ',
  'CLASS:READ',
  'SUBJECT:READ',
  'SEMESTER:READ',
  'COHORT:READ',
  'SECTION:READ'
)
WHERE r.name = 'ROLE_STUDENT'
ON CONFLICT DO NOTHING;

