-- ============================================================
-- CONSOLIDATED SCHEMA — CMS Database
-- Gộp từ: V1 → V4 (trạng thái cuối cùng)
-- Database:  PostgreSQL
-- Dùng cho:  Fresh install — chạy một lần duy nhất
-- Sửa lỗi:  Thêm cột is_deleted vào tất cả bảng (fix lỗi startup)
--            Thêm đầy đủ permissions từ V2/V3
-- ============================================================


-- ============================================================
-- 0. HÀM TIỆN ÍCH
-- ============================================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- ============================================================
-- 1. BẢNG CỐT LÕI
-- ============================================================

CREATE TABLE semesters (
                           id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                           updated_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                           is_deleted       BOOLEAN NOT NULL DEFAULT FALSE,
                           code             VARCHAR(255) NOT NULL,
                           name             VARCHAR(255) NOT NULL,
                           start_date       DATE NOT NULL,
                           end_date         DATE NOT NULL,
                           active           BOOLEAN NOT NULL DEFAULT FALSE,
                           secondary_active BOOLEAN NOT NULL DEFAULT FALSE,
                           CONSTRAINT uk_semesters_code UNIQUE (code)
);
CREATE INDEX idx_semesters_code   ON semesters(code);
CREATE INDEX idx_semesters_active ON semesters(active);
CREATE INDEX idx_semesters_dates  ON semesters(start_date, end_date);
CREATE TRIGGER trg_semesters_updated_at BEFORE UPDATE ON semesters
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


CREATE TABLE users (
                       id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
                       username   VARCHAR(255) NOT NULL,
                       email      VARCHAR(255) NOT NULL,
                       password   VARCHAR(255) NOT NULL,
                       CONSTRAINT uk_users_username UNIQUE (username),
                       CONSTRAINT uk_users_email    UNIQUE (email)
);
CREATE INDEX idx_users_username ON users(username);
CREATE INDEX idx_users_email    ON users(email);
CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


CREATE TABLE departments (
                             id              BIGSERIAL PRIMARY KEY,
                             created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             is_deleted      BOOLEAN NOT NULL DEFAULT FALSE,
                             code            VARCHAR(20)  NOT NULL UNIQUE,
                             name            VARCHAR(255) NOT NULL,
                             description     TEXT,
                             parent_id       BIGINT,
                             head_teacher_id BIGINT,
                             active          BOOLEAN NOT NULL DEFAULT TRUE,
                             FOREIGN KEY (parent_id) REFERENCES departments(id) ON DELETE SET NULL
);
CREATE INDEX idx_departments_code      ON departments(code);
CREATE INDEX idx_departments_active    ON departments(active);
CREATE INDEX idx_departments_parent_id ON departments(parent_id);
CREATE TRIGGER trg_departments_updated_at BEFORE UPDATE ON departments
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


CREATE TABLE teachers (
                          id              BIGSERIAL PRIMARY KEY,
                          created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          is_deleted      BOOLEAN NOT NULL DEFAULT FALSE,
                          user_id         BIGINT NOT NULL UNIQUE,
                          employee_code   VARCHAR(50) NOT NULL UNIQUE,
                          department_id   BIGINT,
                          specialization  VARCHAR(255),
                          title           VARCHAR(100),
                          bio             TEXT,
                          office_location VARCHAR(255),
                          office_hours    VARCHAR(255),
                          phone           VARCHAR(20),
                          active          BOOLEAN NOT NULL DEFAULT TRUE,
                          FOREIGN KEY (user_id)       REFERENCES users(id)       ON DELETE CASCADE,
                          FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE SET NULL
);
CREATE INDEX idx_teachers_user_id       ON teachers(user_id);
CREATE INDEX idx_teachers_employee_code ON teachers(employee_code);
CREATE INDEX idx_teachers_department_id ON teachers(department_id);
CREATE INDEX idx_teachers_active        ON teachers(active);
CREATE TRIGGER trg_teachers_updated_at BEFORE UPDATE ON teachers
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

ALTER TABLE departments
    ADD CONSTRAINT fk_departments_head_teacher
        FOREIGN KEY (head_teacher_id) REFERENCES teachers(id) ON DELETE SET NULL;
CREATE INDEX idx_departments_head_teacher_id ON departments(head_teacher_id);


CREATE TABLE subjects (
                          id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          updated_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          is_deleted     BOOLEAN NOT NULL DEFAULT FALSE,
                          code           VARCHAR(255) NOT NULL,
                          name           VARCHAR(255) NOT NULL,
                          description    TEXT,
                          credits        INTEGER  NOT NULL DEFAULT 3,
                          theory_hours   INTEGER  DEFAULT 0,
                          practice_hours INTEGER  DEFAULT 0,
                          process_weight SMALLINT NOT NULL DEFAULT 40,
                          exam_weight    SMALLINT NOT NULL DEFAULT 60,
                          department_id  BIGINT,
                          active         BOOLEAN NOT NULL DEFAULT TRUE,
                          CONSTRAINT uk_subjects_code UNIQUE (code),
                          CONSTRAINT chk_subjects_grade_weights CHECK (
                              process_weight BETWEEN 0 AND 100
                                  AND exam_weight BETWEEN 0 AND 100
                                  AND process_weight + exam_weight = 100
                              ),
                          FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE SET NULL
);
CREATE INDEX idx_subjects_code          ON subjects(code);
CREATE INDEX idx_subjects_active        ON subjects(active);
CREATE INDEX idx_subjects_department_id ON subjects(department_id);
CREATE TRIGGER trg_subjects_updated_at BEFORE UPDATE ON subjects
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


CREATE TABLE cohorts (
                         id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
                         code       VARCHAR(50)  NOT NULL UNIQUE,
                         name       VARCHAR(255) NOT NULL,
                         start_year INT NOT NULL,
                         end_year   INT NOT NULL,
                         active     BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE TRIGGER trg_cohorts_updated_at BEFORE UPDATE ON cohorts
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


-- ============================================================
-- 2. CHƯƠNG TRÌNH ĐÀO TẠO
-- ============================================================

CREATE TABLE academic_programs (
                                   id            BIGSERIAL PRIMARY KEY,
                                   created_at    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                                   updated_at    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                                   is_deleted    BOOLEAN NOT NULL DEFAULT FALSE,
                                   code          VARCHAR(50)  NOT NULL UNIQUE,
                                   name          VARCHAR(255) NOT NULL,
                                   department_id BIGINT,
                                   total_credits INTEGER NOT NULL,
                                   description   TEXT,
                                    is_active     BOOLEAN DEFAULT TRUE,
                                    CONSTRAINT fk_academic_programs_department FOREIGN KEY (department_id) REFERENCES departments(id)
);
CREATE TRIGGER trg_academic_programs_updated_at BEFORE UPDATE ON academic_programs
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


CREATE TABLE program_subjects (
                                  id           BIGSERIAL PRIMARY KEY,
                                  created_at   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                                  updated_at   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                                  is_deleted   BOOLEAN NOT NULL DEFAULT FALSE,
                                  program_id   BIGINT NOT NULL,
                                  subject_id   BIGINT NOT NULL,
                                  semester     INTEGER NOT NULL CHECK (semester > 0),
                                  subject_type VARCHAR(20) NOT NULL DEFAULT 'COMPULSORY',
                                  pass_score   DOUBLE PRECISION DEFAULT 4.0,
                                  CONSTRAINT uq_program_subject UNIQUE (program_id, subject_id),
                                  FOREIGN KEY (program_id) REFERENCES academic_programs(id) ON DELETE CASCADE,
                                  FOREIGN KEY (subject_id) REFERENCES subjects(id)          ON DELETE CASCADE
);
CREATE INDEX idx_program_subjects_program_id ON program_subjects(program_id);


-- ============================================================
-- 3. LỚP HÀNH CHÍNH & SINH VIÊN
-- ============================================================

CREATE TABLE student_classes (
                                 id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 is_deleted          BOOLEAN NOT NULL DEFAULT FALSE,
                                 code                VARCHAR(50)  NOT NULL,
                                 name                VARCHAR(255) NOT NULL,
                                 department_id       BIGINT,
                                 cohort_id           BIGINT,
                                 intake_year         INTEGER,
                                 program             VARCHAR(255),
                                 advisor_teacher_id  BIGINT,
                                 program_id          BIGINT,
                                 active              BOOLEAN NOT NULL DEFAULT TRUE,
                                 CONSTRAINT uk_student_classes_code UNIQUE (code),
                                 FOREIGN KEY (department_id)      REFERENCES departments(id)      ON DELETE SET NULL,
                                 FOREIGN KEY (cohort_id)          REFERENCES cohorts(id),
                                 FOREIGN KEY (advisor_teacher_id) REFERENCES teachers(id),
                                 FOREIGN KEY (program_id)         REFERENCES academic_programs(id)
);
CREATE INDEX idx_student_classes_code               ON student_classes(code);
CREATE INDEX idx_student_classes_department_id      ON student_classes(department_id);
CREATE INDEX idx_student_classes_intake_year        ON student_classes(intake_year);
CREATE INDEX idx_student_classes_advisor_teacher_id ON student_classes(advisor_teacher_id);
CREATE INDEX idx_student_classes_program_id         ON student_classes(program_id);
CREATE INDEX idx_student_classes_active             ON student_classes(active);
CREATE TRIGGER trg_student_classes_updated_at BEFORE UPDATE ON student_classes
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


CREATE TABLE students (
                          id               BIGSERIAL PRIMARY KEY,
                          created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          updated_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          is_deleted       BOOLEAN NOT NULL DEFAULT FALSE,
                          user_id          BIGINT NOT NULL UNIQUE,
                          student_code     VARCHAR(50) NOT NULL UNIQUE,
                          department_id    BIGINT,
                          student_class_id BIGINT,
                          phone            VARCHAR(20),
                          active           BOOLEAN NOT NULL DEFAULT TRUE,
                          FOREIGN KEY (user_id)          REFERENCES users(id)           ON DELETE CASCADE,
                          FOREIGN KEY (department_id)    REFERENCES departments(id)     ON DELETE SET NULL,
                          FOREIGN KEY (student_class_id) REFERENCES student_classes(id) ON DELETE SET NULL
);
CREATE INDEX idx_students_user_id          ON students(user_id);
CREATE INDEX idx_students_student_code     ON students(student_code);
CREATE INDEX idx_students_department_id    ON students(department_id);
CREATE INDEX idx_students_student_class_id ON students(student_class_id);
CREATE INDEX idx_students_active           ON students(active);
CREATE TRIGGER trg_students_updated_at BEFORE UPDATE ON students
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


-- ============================================================
-- 4. LỚP HỌC PHẦN
-- ============================================================

CREATE TABLE sections (
                          id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          created_at             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          updated_at             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          is_deleted             BOOLEAN NOT NULL DEFAULT FALSE,
                          code                   VARCHAR(255) NOT NULL,
                          name                   VARCHAR(255) NOT NULL,
                          semester_id            BIGINT,
                          subject_id             BIGINT,
                          teacher_id             BIGINT,
                          current_students       INTEGER NOT NULL DEFAULT 0,
                          max_students           INTEGER NOT NULL DEFAULT 30,
                          min_students           INTEGER NOT NULL DEFAULT 0,
                          status                 VARCHAR(20) NOT NULL DEFAULT 'OPEN',
                          registration_enabled   BOOLEAN NOT NULL DEFAULT TRUE,
                          enrollment_start_date  DATE,
                          enrollment_end_date    DATE,
                          canceled_at            TIMESTAMP,
                          canceled_reason        TEXT,
                          merged_into_section_id BIGINT,
                          active                 BOOLEAN NOT NULL DEFAULT TRUE,
                          CONSTRAINT uk_sections_code UNIQUE (code),
                          CONSTRAINT chk_sections_status CHECK (status IN ('OPEN','CLOSED','CANCELED','MERGED')),
                          FOREIGN KEY (semester_id)            REFERENCES semesters(id) ON DELETE SET NULL,
                          FOREIGN KEY (subject_id)             REFERENCES subjects(id)  ON DELETE SET NULL,
                          FOREIGN KEY (teacher_id)             REFERENCES users(id)     ON DELETE SET NULL,
                          FOREIGN KEY (merged_into_section_id) REFERENCES sections(id)  ON DELETE SET NULL
);
CREATE INDEX idx_sections_code        ON sections(code);
CREATE INDEX idx_sections_semester_id ON sections(semester_id);
CREATE INDEX idx_sections_subject_id  ON sections(subject_id);
CREATE INDEX idx_sections_teacher_id  ON sections(teacher_id);
CREATE INDEX idx_sections_status      ON sections(status);
CREATE INDEX idx_sections_active      ON sections(active);
CREATE TRIGGER trg_sections_updated_at BEFORE UPDATE ON sections
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


CREATE TABLE section_time_slots (
                                    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                    is_deleted  BOOLEAN NOT NULL DEFAULT FALSE,
                                    section_id  BIGINT NOT NULL,
                                    day_of_week SMALLINT NOT NULL,
                                    start_time  TIME NOT NULL,
                                    end_time    TIME NOT NULL,
                                    room        VARCHAR(50),
                                    FOREIGN KEY (section_id) REFERENCES sections(id) ON DELETE CASCADE
);
CREATE INDEX idx_section_time_slots_section_id ON section_time_slots(section_id);
CREATE TRIGGER trg_section_time_slots_updated_at BEFORE UPDATE ON section_time_slots
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


CREATE TABLE enrollments (
                             id                            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             created_at                    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             updated_at                    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             is_deleted                    BOOLEAN NOT NULL DEFAULT FALSE,
                             section_id                    BIGINT NOT NULL,
                             student_id                    BIGINT NOT NULL,
                             status                        VARCHAR(50),
                             process_score                 NUMERIC(4,2),
                             exam_score                    NUMERIC(4,2),
                             final_score                   NUMERIC(4,2),
                             scored_at                     TIMESTAMP,
                             score_locked                  BOOLEAN NOT NULL DEFAULT FALSE,
                             score_overridden              BOOLEAN NOT NULL DEFAULT FALSE,
                             score_override_reason         TEXT,
                             score_overridden_at           TIMESTAMP,
                             process_score_before_override NUMERIC(4,2),
                             exam_score_before_override    NUMERIC(4,2),
                             final_score_before_override   NUMERIC(4,2),
                             CONSTRAINT uk_enrollments_section_student UNIQUE (section_id, student_id),
                             FOREIGN KEY (section_id) REFERENCES sections(id)  ON DELETE CASCADE,
                             FOREIGN KEY (student_id) REFERENCES students(id)  ON DELETE CASCADE
);
CREATE INDEX idx_enrollments_section_id ON enrollments(section_id);
CREATE INDEX idx_enrollments_student_id ON enrollments(student_id);
CREATE INDEX idx_enrollments_status     ON enrollments(status);
CREATE TRIGGER trg_enrollments_updated_at BEFORE UPDATE ON enrollments
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


-- ============================================================
-- 5. RBAC
-- ============================================================

CREATE TABLE roles (
                       id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       is_deleted  BOOLEAN NOT NULL DEFAULT FALSE,
                       name        VARCHAR(100) NOT NULL,
                       description VARCHAR(255),
                       CONSTRAINT uk_roles_name UNIQUE (name)
);
CREATE TRIGGER trg_roles_updated_at BEFORE UPDATE ON roles
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


CREATE TABLE permissions (
                             id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             is_deleted  BOOLEAN NOT NULL DEFAULT FALSE,
                             name        VARCHAR(100) NOT NULL,
                             resource    VARCHAR(100) NOT NULL,
                             action      VARCHAR(100) NOT NULL,
                             description VARCHAR(255),
                             CONSTRAINT uk_permissions_name UNIQUE (name)
);
CREATE TRIGGER trg_permissions_updated_at BEFORE UPDATE ON permissions
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


CREATE TABLE role_permissions (
                                  role_id       BIGINT NOT NULL,
                                  permission_id BIGINT NOT NULL,
                                  PRIMARY KEY (role_id, permission_id),
                                  FOREIGN KEY (role_id)       REFERENCES roles(id)       ON DELETE CASCADE,
                                  FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE
);


CREATE TABLE user_roles (
                             user_id BIGINT NOT NULL,
                             role_id BIGINT NOT NULL,
                             PRIMARY KEY (user_id, role_id),
                             FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
                             FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);


-- ============================================================
-- 5.1. AUDIT
-- ============================================================

CREATE TABLE auth_audit_events (
                                   id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                   updated_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                   is_deleted        BOOLEAN NOT NULL DEFAULT FALSE,
                                   username          VARCHAR(255),
                                   event_type        VARCHAR(255) NOT NULL,
                                   success           BOOLEAN NOT NULL,
                                   ip                VARCHAR(45),
                                   user_agent        VARCHAR(500),
                                   session_id        VARCHAR(255),
                                   details           TEXT
);
CREATE INDEX idx_auth_audit_events_username ON auth_audit_events(username);
CREATE INDEX idx_auth_audit_events_created_at ON auth_audit_events(created_at);
CREATE TRIGGER trg_auth_audit_events_updated_at BEFORE UPDATE ON auth_audit_events
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


-- ============================================================
-- 6. SEED: ROLES & PERMISSIONS
-- ============================================================

INSERT INTO roles (name, description) VALUES
                                          ('ROLE_ADMIN',   'Administrator - toàn quyền'),
                                          ('ROLE_TEACHER', 'Giảng viên'),
                                          ('ROLE_STUDENT', 'Sinh viên');

INSERT INTO permissions (name, resource, action, description) VALUES
                                                                  ('USER:CREATE',              'USER',             'CREATE',   'Create user'),
                                                                  ('USER:READ',                'USER',             'READ',     'Read user'),
                                                                  ('USER:UPDATE',              'USER',             'UPDATE',   'Update user'),
                                                                  ('USER:DELETE',              'USER',             'DELETE',   'Delete user'),
                                                                  ('ENROLLMENT:CREATE',        'ENROLLMENT',       'CREATE',   'Create enrollment'),
                                                                  ('ENROLLMENT:READ',          'ENROLLMENT',       'READ',     'Read enrollment'),
                                                                  ('ENROLLMENT:UPDATE',        'ENROLLMENT',       'UPDATE',   'Update enrollment'),
                                                                  ('ENROLLMENT:DELETE',        'ENROLLMENT',       'DELETE',   'Delete enrollment'),
                                                                  ('DEPARTMENT:CREATE',        'DEPARTMENT',       'CREATE',   'Create department'),
                                                                  ('DEPARTMENT:READ',          'DEPARTMENT',       'READ',     'Read department'),
                                                                  ('DEPARTMENT:UPDATE',        'DEPARTMENT',       'UPDATE',   'Update department'),
                                                                  ('DEPARTMENT:DELETE',        'DEPARTMENT',       'DELETE',   'Delete department'),
                                                                  ('SUBJECT:CREATE',           'SUBJECT',          'CREATE',   'Create subject'),
                                                                  ('SUBJECT:READ',             'SUBJECT',          'READ',     'Read subject'),
                                                                  ('SUBJECT:UPDATE',           'SUBJECT',          'UPDATE',   'Update subject'),
                                                                  ('SUBJECT:DELETE',           'SUBJECT',          'DELETE',   'Delete subject'),
                                                                  ('SEMESTER:CREATE',          'SEMESTER',         'CREATE',   'Create semester'),
                                                                  ('SEMESTER:READ',            'SEMESTER',         'READ',     'Read semester'),
                                                                  ('SEMESTER:UPDATE',          'SEMESTER',         'UPDATE',   'Update semester'),
                                                                  ('SEMESTER:DELETE',          'SEMESTER',         'DELETE',   'Delete semester'),
                                                                  ('COHORT:CREATE',            'COHORT',           'CREATE',   'Create cohort'),
                                                                  ('COHORT:READ',              'COHORT',           'READ',     'Read cohort'),
                                                                  ('COHORT:UPDATE',            'COHORT',           'UPDATE',   'Update cohort'),
                                                                  ('COHORT:DELETE',            'COHORT',           'DELETE',   'Delete cohort'),
                                                                  ('SECTION:CREATE',           'SECTION',          'CREATE',   'Create section'),
                                                                  ('SECTION:READ',             'SECTION',          'READ',     'Read section'),
                                                                  ('SECTION:UPDATE',           'SECTION',          'UPDATE',   'Update section'),
                                                                  ('SECTION:DELETE',           'SECTION',          'DELETE',   'Delete section'),
                                                                  ('TEACHER:CREATE',           'TEACHER',          'CREATE',   'Create teacher'),
                                                                  ('TEACHER:READ',             'TEACHER',          'READ',     'Read teacher'),
                                                                  ('TEACHER:UPDATE',           'TEACHER',          'UPDATE',   'Update teacher'),
                                                                  ('TEACHER:DELETE',           'TEACHER',          'DELETE',   'Delete teacher'),
                                                                  ('STUDENT:CREATE',           'STUDENT',          'CREATE',   'Create student'),
                                                                  ('STUDENT:READ',             'STUDENT',          'READ',     'Read student'),
                                                                  ('STUDENT:UPDATE',           'STUDENT',          'UPDATE',   'Update student'),
                                                                  ('STUDENT:DELETE',           'STUDENT',          'DELETE',   'Delete student'),
                                                                  ('STUDENT_CLASS:CREATE',     'STUDENT_CLASS',    'CREATE',   'Create student class'),
                                                                  ('STUDENT_CLASS:READ',       'STUDENT_CLASS',    'READ',     'Read student class'),
                                                                  ('STUDENT_CLASS:UPDATE',     'STUDENT_CLASS',    'UPDATE',   'Update student class'),
                                                                  ('STUDENT_CLASS:DELETE',     'STUDENT_CLASS',    'DELETE',   'Delete student class'),
                                                                  ('ACADEMIC_PROGRAM:READ',    'ACADEMIC_PROGRAM', 'READ',     'Xem chương trình đào tạo'),
                                                                  ('ACADEMIC_PROGRAM:CREATE',  'ACADEMIC_PROGRAM', 'CREATE',   'Tạo chương trình đào tạo'),
                                                                  ('ACADEMIC_PROGRAM:UPDATE',  'ACADEMIC_PROGRAM', 'UPDATE',   'Cập nhật chương trình đào tạo'),
                                                                  ('ACADEMIC_PROGRAM:DELETE',  'ACADEMIC_PROGRAM', 'DELETE',   'Xóa chương trình đào tạo'),
                                                                  ('STUDENT_PROGRESS:READ_ALL',  'STUDENT_PROGRESS', 'READ_ALL',  'Xem tiến độ học tập (Tất cả)'),
                                                                  ('STUDENT_PROGRESS:READ_CLASS','STUDENT_PROGRESS', 'READ_CLASS','Xem tiến độ học tập (Lớp chủ nhiệm)'),
                                                                  ('STUDENT_PROGRESS:READ_SELF', 'STUDENT_PROGRESS', 'READ_SELF', 'Xem tiến độ học tập (Cá nhân)');

-- ROLE_ADMIN: tất cả permissions
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.name = 'ROLE_ADMIN';

-- ROLE_TEACHER
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r, permissions p
WHERE r.name = 'ROLE_TEACHER'
  AND p.name IN (
                 'DEPARTMENT:READ', 'SUBJECT:READ', 'SEMESTER:READ', 'COHORT:READ',
                 'SECTION:READ', 'STUDENT_CLASS:READ', 'TEACHER:READ',
                 'ENROLLMENT:READ', 'ENROLLMENT:UPDATE',
                 'ACADEMIC_PROGRAM:READ', 'STUDENT_PROGRESS:READ_CLASS'
    );

-- ROLE_STUDENT
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r, permissions p
WHERE r.name = 'ROLE_STUDENT'
  AND p.name IN (
                 'SUBJECT:READ', 'SEMESTER:READ', 'SECTION:READ', 'COHORT:READ',
                 'ENROLLMENT:READ', 'ENROLLMENT:CREATE', 'ENROLLMENT:DELETE',
                 'ACADEMIC_PROGRAM:READ', 'STUDENT_PROGRESS:READ_SELF'
    );


-- ============================================================
-- 7. VIEW
-- ============================================================

CREATE OR REPLACE VIEW v_sections_with_teacher AS
SELECT
    s.id                   AS section_id,
    s.code                 AS section_code,
    s.name                 AS section_name,
    s.semester_id,
    s.subject_id,
    s.current_students,
    s.max_students,
    s.status,
    s.registration_enabled,
    subj.code              AS subject_code,
    subj.name              AS subject_name,
    subj.credits,
    sem.code               AS semester_code,
    sem.name               AS semester_name,
    sem.active             AS semester_active,
    u.id                   AS teacher_user_id,
    u.username             AS teacher_username,
    u.email                AS teacher_email,
    t.id                   AS teacher_id,
    t.employee_code,
    t.title                AS teacher_title,
    d.code                 AS department_code,
    d.name                 AS department_name
FROM sections s
         LEFT JOIN subjects    subj ON s.subject_id    = subj.id
         LEFT JOIN semesters   sem  ON s.semester_id   = sem.id
         LEFT JOIN users       u    ON s.teacher_id    = u.id
         LEFT JOIN teachers    t    ON t.user_id       = u.id
         LEFT JOIN departments d    ON t.department_id = d.id;