-- ============================================================
-- CONSOLIDATED SCHEMA
-- Generated from migrations: V1 → V1_1 → V2 → V3 → V4–V6 (dropped)
--                            → V7 → V8 → V9 → V10 → V11 → V12
--                            → V13 → V14 → V15 → V16 → V17
-- Represents the final database state after all migrations.
-- PostgreSQL
-- ============================================================


-- ============================================================
-- SECTION 1: CORE TABLES
-- ============================================================

-- TABLE: semesters
CREATE TABLE semesters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    active BOOLEAN NOT NULL,
    code VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT uk_semesters_code UNIQUE (code)
);

CREATE INDEX idx_semesters_code ON semesters(code);
CREATE INDEX idx_semesters_active ON semesters(active);
CREATE INDEX idx_semesters_dates ON semesters(start_date, end_date);


-- TABLE: subjects
-- Note: V1 had 'credit'; V11 merged it into 'credits' and dropped 'credit'.
CREATE TABLE subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    active BOOLEAN NOT NULL,
    code VARCHAR(255) NOT NULL,
    description TEXT,
    name VARCHAR(255) NOT NULL,
    -- V3: added credits, theory_hours, practice_hours, department_id, prerequisite_subject_ids
    -- V11: finalized credits as NOT NULL DEFAULT 3 (merged from legacy 'credit')
    credits INTEGER NOT NULL DEFAULT 3,
    theory_hours INTEGER DEFAULT 0,
    practice_hours INTEGER DEFAULT 0,
    department_id BIGINT,
    prerequisite_subject_ids BIGINT[],
    CONSTRAINT uk_subjects_code UNIQUE (code)
);

CREATE INDEX idx_subjects_code ON subjects(code);
CREATE INDEX idx_subjects_active ON subjects(active);
CREATE INDEX idx_subjects_department_id ON subjects(department_id);


-- TABLE: users
-- Note: 'role' column existed in V1 but was dropped in V7.
--       'avatar' added in V8.
--       Security fields added in V13.
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    -- V8
    avatar VARCHAR(255),
    -- V13
    failed_login_attempts INTEGER NOT NULL DEFAULT 0,
    lock_until TIMESTAMP NULL,
    last_login_at TIMESTAMP NULL,
    last_login_ip VARCHAR(64) NULL,
    last_login_user_agent TEXT NULL,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT uk_users_username UNIQUE (username)
);

CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_username ON users(username);


-- ============================================================
-- SECTION 2: ACADEMIC STRUCTURE (V3)
-- ============================================================

-- TABLE: departments
CREATE TABLE departments (
    id BIGSERIAL PRIMARY KEY,
    code VARCHAR(20) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    parent_id BIGINT,
    head_teacher_id BIGINT,              -- FK to teachers added after teachers table
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (parent_id) REFERENCES departments(id) ON DELETE SET NULL
);

CREATE INDEX idx_departments_code ON departments(code);
CREATE INDEX idx_departments_active ON departments(active);
CREATE INDEX idx_departments_parent_id ON departments(parent_id);


-- TABLE: teachers
CREATE TABLE teachers (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    employee_code VARCHAR(50) NOT NULL UNIQUE,
    department_id BIGINT,
    specialization VARCHAR(255),
    title VARCHAR(100),
    bio TEXT,
    office_location VARCHAR(255),
    office_hours VARCHAR(255),
    phone VARCHAR(20),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE SET NULL
);

CREATE INDEX idx_teachers_user_id ON teachers(user_id);
CREATE INDEX idx_teachers_employee_code ON teachers(employee_code);
CREATE INDEX idx_teachers_department_id ON teachers(department_id);
CREATE INDEX idx_teachers_active ON teachers(active);


-- Complete departments FK to teachers (now that teachers table exists)
ALTER TABLE departments
    ADD CONSTRAINT fk_departments_head_teacher
    FOREIGN KEY (head_teacher_id) REFERENCES teachers(id) ON DELETE SET NULL;

CREATE INDEX idx_departments_head_teacher_id ON departments(head_teacher_id);


-- TABLE: students  (V15)
-- Profiles for users with ROLE_STUDENT; enrollments.student_id now references this table.
CREATE TABLE students (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    student_code VARCHAR(50) NOT NULL UNIQUE,
    department_id BIGINT,
    phone VARCHAR(20),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE SET NULL
);

CREATE INDEX idx_students_user_id ON students(user_id);
CREATE INDEX idx_students_student_code ON students(student_code);
CREATE INDEX idx_students_department_id ON students(department_id);
CREATE INDEX idx_students_active ON students(active);


-- Add subjects FK to departments (defined after departments exists)
ALTER TABLE subjects
    ADD CONSTRAINT fk_subjects_department
    FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE SET NULL;


-- ============================================================
-- SECTION 3: COURSES & ENROLLMENTS
-- ============================================================

-- TABLE: courses
-- Final state after V3 additions, V10 column removals, V12 teacher FK migration, V16 enrollment window.
-- Note: V10 dropped description, thumbnail_url, status, credits, department_id,
--       duration_weeks, level, language. V16 uses enrollment_start_date/end_date,
--       so those are retained in the final schema.
--       V17 sets DEFAULT 3 on credits — but since V10 dropped credits and no later
--       migration re-adds it, the credits column is NOT included here.
CREATE TABLE courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    active BOOLEAN NOT NULL,
    code VARCHAR(255) NOT NULL,
    current_students INTEGER NOT NULL,
    max_students INTEGER NOT NULL,
    name VARCHAR(255) NOT NULL,
    semester_id BIGINT NOT NULL,
    subject_id BIGINT NOT NULL,
    -- V12: teacher_id now references teachers(id), not users(id)
    teacher_id BIGINT,
    -- V16: enrollment window columns (originally V3, retained through V16)
    enrollment_start_date DATE,
    enrollment_end_date DATE,
    CONSTRAINT uk_courses_code UNIQUE (code),
    CONSTRAINT fk_courses_semester FOREIGN KEY (semester_id) REFERENCES semesters(id),
    CONSTRAINT fk_courses_subject FOREIGN KEY (subject_id) REFERENCES subjects(id),
    CONSTRAINT fk_courses_teacher FOREIGN KEY (teacher_id) REFERENCES teachers(id) ON DELETE SET NULL
);

CREATE INDEX idx_courses_semester_id ON courses(semester_id);
CREATE INDEX idx_courses_subject_id ON courses(subject_id);
CREATE INDEX idx_courses_teacher_id ON courses(teacher_id);
CREATE INDEX idx_courses_active ON courses(active);


-- TABLE: enrollments
-- Final state after V15: student_id references students(id) instead of users(id).
CREATE TABLE enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    grade DOUBLE PRECISION,
    status VARCHAR(255) NOT NULL,
    course_id BIGINT NOT NULL,
    -- V15: student_id now references students(id)
    student_id BIGINT NOT NULL,
    CONSTRAINT uk_enrollments_course_student UNIQUE (course_id, student_id),
    CONSTRAINT fk_enrollments_course FOREIGN KEY (course_id) REFERENCES courses(id),
    CONSTRAINT fk_enrollments_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
);

CREATE INDEX idx_enrollments_course_id ON enrollments(course_id);
CREATE INDEX idx_enrollments_student_id ON enrollments(student_id);
CREATE INDEX idx_enrollments_status ON enrollments(status);


-- TABLE: course_time_slots  (V16)
CREATE TABLE course_time_slots (
    id BIGSERIAL PRIMARY KEY,
    course_id BIGINT NOT NULL,
    day_of_week SMALLINT NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_course_time_slots_course FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
    CONSTRAINT chk_course_time_slots_day CHECK (day_of_week BETWEEN 1 AND 7),
    CONSTRAINT chk_course_time_slots_time CHECK (start_time < end_time)
);

CREATE UNIQUE INDEX uk_course_time_slots_course_day_time
    ON course_time_slots(course_id, day_of_week, start_time, end_time);

CREATE INDEX idx_course_time_slots_course_id ON course_time_slots(course_id);
CREATE INDEX idx_course_time_slots_day_of_week ON course_time_slots(day_of_week);


-- ============================================================
-- SECTION 4: RBAC & AUTHENTICATION  (V2)
-- ============================================================

-- TABLE: roles
CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_roles_name ON roles(name);


-- TABLE: permissions
CREATE TABLE permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    resource VARCHAR(50) NOT NULL,
    action VARCHAR(50) NOT NULL,
    description VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_permissions_resource_action ON permissions(resource, action);


-- TABLE: role_permissions
CREATE TABLE role_permissions (
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    granted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permissions_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
    CONSTRAINT fk_role_permissions_permission FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE
);


-- TABLE: user_roles
CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

CREATE INDEX idx_user_roles_user_id ON user_roles(user_id);


-- TABLE: refresh_tokens
CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(255) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    revoked_at TIMESTAMP,
    replaced_by_token VARCHAR(255),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_refresh_tokens_token ON refresh_tokens(token);
CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens(user_id);
CREATE INDEX idx_refresh_tokens_expires_at ON refresh_tokens(expires_at);


-- TABLE: password_reset_tokens
CREATE TABLE password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(255) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    used_at TIMESTAMP,
    CONSTRAINT fk_password_reset_tokens_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_password_reset_tokens_token ON password_reset_tokens(token);
CREATE INDEX idx_password_reset_tokens_user_id ON password_reset_tokens(user_id);
CREATE INDEX idx_password_reset_tokens_expires_at ON password_reset_tokens(expires_at);


-- TABLE: auth_audit_events  (V14)
CREATE TABLE auth_audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    username VARCHAR(255),
    event_type VARCHAR(64) NOT NULL,
    success BOOLEAN NOT NULL,
    ip VARCHAR(64),
    user_agent TEXT,
    session_id VARCHAR(64),
    details TEXT
);


-- ============================================================
-- SECTION 5: TRIGGERS & FUNCTIONS
-- ============================================================

-- Generic updated_at auto-update function  (V1_1)
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_users_updated_at
    BEFORE UPDATE ON users FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_update_courses_updated_at
    BEFORE UPDATE ON courses FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_update_enrollments_updated_at
    BEFORE UPDATE ON enrollments FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_update_subjects_updated_at
    BEFORE UPDATE ON subjects FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_update_semesters_updated_at
    BEFORE UPDATE ON semesters FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_update_roles_updated_at
    BEFORE UPDATE ON roles FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_update_permissions_updated_at
    BEFORE UPDATE ON permissions FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_update_refresh_tokens_updated_at
    BEFORE UPDATE ON refresh_tokens FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_update_password_reset_tokens_updated_at
    BEFORE UPDATE ON password_reset_tokens FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();


-- ============================================================
-- SECTION 6: VIEWS
-- ============================================================

-- VIEW: v_courses_with_teacher
-- Final version from V12: teacher_id references teachers(id)
CREATE OR REPLACE VIEW v_courses_with_teacher AS
SELECT
    c.id            AS course_id,
    c.code          AS course_code,
    c.name          AS course_name,
    c.semester_id,
    c.subject_id,
    c.current_students,
    c.max_students,
    s.name          AS subject_name,
    sem.name        AS semester_name,
    t.id            AS teacher_id,
    t.user_id       AS teacher_user_id,
    u.username      AS teacher_username,
    u.email         AS teacher_email,
    t.employee_code,
    d.code          AS department_code,
    d.name          AS department_name
FROM courses c
LEFT JOIN subjects s   ON c.subject_id = s.id
LEFT JOIN semesters sem ON c.semester_id = sem.id
LEFT JOIN teachers t   ON c.teacher_id = t.id
LEFT JOIN users u      ON t.user_id = u.id
LEFT JOIN departments d ON t.department_id = d.id;


-- ============================================================
-- SECTION 7: SEED DATA
-- ============================================================

-- Semesters  (V1)
INSERT INTO semesters (id, created_at, updated_at, active, code, start_date, end_date, name) VALUES
    (1, '2026-02-10 12:27:12', '2026-02-10 12:27:12', TRUE,  'HK1_2425', '2024-09-01', '2025-01-15', 'Học kỳ 1 2024-2025'),
    (2, '2026-02-10 12:27:12', '2026-02-10 12:27:12', FALSE, 'HK2_2425', '2025-01-20', '2025-06-15', 'Học kỳ 2 2024-2025');

SELECT setval('semesters_id_seq', (SELECT MAX(id) FROM semesters), true);


-- Subjects  (V1 + V11: 'credit' → 'credits')
INSERT INTO subjects (id, created_at, updated_at, active, code, description, name, credits) VALUES
    (1, '2026-02-10 12:27:12', '2026-02-10 12:27:12', TRUE, 'JAVA001', 'Môn học cung cấp kiến thức nền tảng về ngôn ngữ lập trình Java.', 'Lập trình Java căn bản', 3),
    (2, '2026-02-10 12:27:12', '2026-02-10 12:27:12', TRUE, 'WEB002',  'Xây dựng ứng dụng web hiện đại sử dụng Spring Boot framework.',  'Lập trình Web với Spring Boot', 4),
    (3, '2026-02-10 12:27:12', '2026-02-10 12:27:12', TRUE, 'DB003',   'Kiến thức về thiết kế và quản trị cơ sở dữ liệu quan hệ.',      'Cơ sở dữ liệu', 3);

SELECT setval('subjects_id_seq', (SELECT MAX(id) FROM subjects), true);


-- Users  (V1; 'role' column dropped by V7 — not included here)
INSERT INTO users (id, created_at, updated_at, email, password, username) VALUES
    (3, '2026-02-10 12:27:12', '2026-02-10 12:27:12', 'admin@nws.com.vn',
     '$2a$10$H5mjFs1H.VUbzZnmZgNwxOopdEOI/eaob2QNrs5GQeIi/YfQSQA/u', 'admin'),
    (4, '2026-02-10 12:27:12', '2026-02-10 12:27:12', 'teacher@nws.com.vn',
     '$2a$10$ilFd7HwXVEYrwrYjRBo5aefJ9vY1xKe8VkrmPRtcHTEGHzNCGJeq.', 'teacher'),
    (5, '2026-02-10 12:27:12', '2026-02-10 12:27:12', 'student@nws.com.vn',
     '$2a$10$jZh02f/DBaYNxVtz/Fk.w.uEVLg/JxBgjTBZvcsnh4BclMI5rj/s6', 'student');

SELECT setval('users_id_seq', (SELECT MAX(id) FROM users), true);


-- Departments  (V3)
INSERT INTO departments (code, name, description, active) VALUES
    ('IT',  'Khoa Công nghệ Thông tin',  'Khoa chuyên đào tạo về lập trình, mạng máy tính, AI',         TRUE),
    ('BUS', 'Khoa Quản trị Kinh doanh', 'Khoa chuyên đào tạo về quản trị, marketing, tài chính',        TRUE),
    ('ENG', 'Khoa Ngoại ngữ',           'Khoa chuyên đào tạo tiếng Anh, tiếng Nhật, tiếng Trung',       TRUE);

-- Set default department for subjects  (V3)
UPDATE subjects
SET department_id = (SELECT id FROM departments WHERE code = 'IT' LIMIT 1)
WHERE department_id IS NULL;


-- Teachers  (V12: backfilled teacher profile for user_id=4)
INSERT INTO teachers (user_id, employee_code, active, created_at, updated_at) VALUES
    (4, 'GV000004', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


-- Courses  (V1 + V12: teacher_id now points to teachers.id)
INSERT INTO courses (id, created_at, updated_at, active, code, current_students, max_students, name,
                     semester_id, subject_id, teacher_id,
                     enrollment_start_date, enrollment_end_date)
VALUES
    (1, '2026-02-10 12:27:12', '2026-02-10 12:27:12', TRUE,
     'JAVA001_HK1_01', 0, 30, 'Lớp Java 01 - HK1',
     1, 1,
     (SELECT id FROM teachers WHERE user_id = 4),
     CURRENT_DATE, CURRENT_DATE + INTERVAL '365 days');

SELECT setval('courses_id_seq', (SELECT MAX(id) FROM courses), true);


-- Roles  (V2)
INSERT INTO roles (id, name, description, created_at, updated_at) VALUES
    (1, 'ROLE_ADMIN',   'Administrator - Full system access',          CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, 'ROLE_TEACHER', 'Teacher - Can manage courses and students',   CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (3, 'ROLE_STUDENT', 'Student - Can enroll and learn',              CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

SELECT setval('roles_id_seq', (SELECT MAX(id) FROM roles), true);


-- Permissions  (V2)
INSERT INTO permissions (name, resource, action, description, created_at, updated_at) VALUES
    ('COURSE:CREATE',     'COURSE',     'CREATE',  'Create new course',    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('COURSE:READ',       'COURSE',     'READ',    'View course details',  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('COURSE:UPDATE',     'COURSE',     'UPDATE',  'Update course',        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('COURSE:DELETE',     'COURSE',     'DELETE',  'Delete course',        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('COURSE:PUBLISH',    'COURSE',     'PUBLISH', 'Publish course',       CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('USER:CREATE',       'USER',       'CREATE',  'Create new user',      CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('USER:READ',         'USER',       'READ',    'View user details',    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('USER:UPDATE',       'USER',       'UPDATE',  'Update user',          CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('USER:DELETE',       'USER',       'DELETE',  'Delete user',          CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ENROLLMENT:CREATE', 'ENROLLMENT', 'CREATE',  'Enroll student',       CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ENROLLMENT:READ',   'ENROLLMENT', 'READ',    'View enrollment',      CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ENROLLMENT:UPDATE', 'ENROLLMENT', 'UPDATE',  'Update enrollment',    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ENROLLMENT:DELETE', 'ENROLLMENT', 'DELETE',  'Cancel enrollment',    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


-- Role-Permission assignments  (V2)
-- ADMIN: all permissions
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p WHERE r.name = 'ROLE_ADMIN';

-- TEACHER: all COURSE + USER:READ + all ENROLLMENT
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r, permissions p
WHERE r.name = 'ROLE_TEACHER'
  AND (p.resource = 'COURSE'
       OR (p.resource = 'USER' AND p.action = 'READ')
       OR p.resource = 'ENROLLMENT');

-- STUDENT: COURSE:READ + ENROLLMENT:CREATE + ENROLLMENT:READ
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r, permissions p
WHERE r.name = 'ROLE_STUDENT'
  AND ((p.resource = 'COURSE' AND p.action = 'READ')
       OR (p.resource = 'ENROLLMENT' AND p.action IN ('CREATE', 'READ')));


-- User-Role assignments  (V2 — mapped from legacy role column values)
INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id FROM users u, roles r
WHERE (u.username = 'admin'   AND r.name = 'ROLE_ADMIN')
   OR (u.username = 'teacher' AND r.name = 'ROLE_TEACHER')
   OR (u.username = 'student' AND r.name = 'ROLE_STUDENT');


-- Students  (V15: backfilled profile for student user)
INSERT INTO students (user_id, student_code, active, created_at, updated_at)
SELECT u.id, ('SV' || u.id::text), TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM users u
WHERE u.username = 'student'
  AND NOT EXISTS (SELECT 1 FROM students s WHERE s.user_id = u.id);


-- Reset remaining sequences
SELECT setval('departments_id_seq',  (SELECT COALESCE(MAX(id), 1) FROM departments),  true);
SELECT setval('teachers_id_seq',     (SELECT COALESCE(MAX(id), 1) FROM teachers),     true);
SELECT setval('students_id_seq',     (SELECT COALESCE(MAX(id), 1) FROM students),     true);
SELECT setval('enrollments_id_seq',  (SELECT COALESCE(MAX(id), 1) FROM enrollments),  true);
