-- ============================================================
-- CONSOLIDATED MIGRATION SCRIPT
-- Tổng hợp từ: V1 → V25
-- Database: PostgreSQL
-- Ghi chú: File này thay thế toàn bộ V1–V25 cho fresh install.
-- ============================================================


-- ============================================================
-- PHẦN 0: HÀM TIỆN ÍCH
-- ============================================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- ============================================================
-- PHẦN 1: BẢNG CỐT LÕI
-- ============================================================

CREATE TABLE semesters (
                           id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                           updated_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                           active           BOOLEAN NOT NULL DEFAULT FALSE,
                           secondary_active BOOLEAN NOT NULL DEFAULT FALSE,
                           code             VARCHAR(255) NOT NULL,
                           start_date       DATE NOT NULL,
                           end_date         DATE NOT NULL,
                           name             VARCHAR(255) NOT NULL,
                           CONSTRAINT uk_semesters_code UNIQUE (code)
);
CREATE INDEX idx_semesters_code   ON semesters(code);
CREATE INDEX idx_semesters_active ON semesters(active);
CREATE INDEX idx_semesters_dates  ON semesters(start_date, end_date);
CREATE TRIGGER trg_update_semesters_updated_at
    BEFORE UPDATE ON semesters FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


CREATE TABLE users (
                       id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       email      VARCHAR(255) NOT NULL,
                       password   VARCHAR(255) NOT NULL,
                       username   VARCHAR(255) NOT NULL,
                       CONSTRAINT uk_users_email    UNIQUE (email),
                       CONSTRAINT uk_users_username UNIQUE (username)
);
CREATE INDEX idx_users_email    ON users(email);
CREATE INDEX idx_users_username ON users(username);
CREATE TRIGGER trg_update_users_updated_at
    BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


CREATE TABLE departments (
                             id              BIGSERIAL PRIMARY KEY,
                             code            VARCHAR(20)  NOT NULL UNIQUE,
                             name            VARCHAR(255) NOT NULL,
                             description     TEXT,
                             parent_id       BIGINT,
                             head_teacher_id BIGINT,
                             active          BOOLEAN NOT NULL DEFAULT TRUE,
                             created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             FOREIGN KEY (parent_id) REFERENCES departments(id) ON DELETE SET NULL
);
CREATE INDEX idx_departments_code      ON departments(code);
CREATE INDEX idx_departments_active    ON departments(active);
CREATE INDEX idx_departments_parent_id ON departments(parent_id);
CREATE TRIGGER trg_update_departments_updated_at
    BEFORE UPDATE ON departments FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


CREATE TABLE teachers (
                          id              BIGSERIAL PRIMARY KEY,
                          user_id         BIGINT NOT NULL UNIQUE,
                          employee_code   VARCHAR(50) NOT NULL UNIQUE,
                          department_id   BIGINT,
                          specialization  VARCHAR(255),
                          title           VARCHAR(100),
                          bio             TEXT,
                          office_location VARCHAR(255),
                          office_hours    VARCHAR(255),
                          phone           VARCHAR(20),
                          active          BOOLEAN NOT NULL DEFAULT TRUE,
                          created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          FOREIGN KEY (user_id)       REFERENCES users(id)       ON DELETE CASCADE,
                          FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE SET NULL
);
CREATE INDEX idx_teachers_user_id       ON teachers(user_id);
CREATE INDEX idx_teachers_employee_code ON teachers(employee_code);
CREATE INDEX idx_teachers_department_id ON teachers(department_id);
CREATE INDEX idx_teachers_active        ON teachers(active);
CREATE TRIGGER trg_update_teachers_updated_at
    BEFORE UPDATE ON teachers FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Hoàn thiện FK departments → teachers (deferred vì teachers tạo sau)
ALTER TABLE departments
    ADD CONSTRAINT fk_departments_head_teacher
        FOREIGN KEY (head_teacher_id) REFERENCES teachers(id) ON DELETE SET NULL;
CREATE INDEX idx_departments_head_teacher_id ON departments(head_teacher_id);


CREATE TABLE subjects (
                          id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          updated_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          active         BOOLEAN NOT NULL DEFAULT TRUE,
                          code           VARCHAR(255) NOT NULL,
                          description    TEXT,
                          name           VARCHAR(255) NOT NULL,
                          credits        INTEGER  NOT NULL DEFAULT 3,
                          theory_hours   INTEGER  DEFAULT 0,
                          practice_hours INTEGER  DEFAULT 0,
                          department_id  BIGINT,
                          process_weight SMALLINT NOT NULL DEFAULT 40,
                          exam_weight    SMALLINT NOT NULL DEFAULT 60,
                          CONSTRAINT uk_subjects_code UNIQUE (code),
                          CONSTRAINT chk_subjects_grade_weights CHECK (
                              process_weight BETWEEN 0 AND 100
                                  AND exam_weight BETWEEN 0 AND 100
                                  AND (process_weight + exam_weight = 100)
                              ),
                          FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE SET NULL
);
CREATE INDEX idx_subjects_code          ON subjects(code);
CREATE INDEX idx_subjects_active        ON subjects(active);
CREATE INDEX idx_subjects_department_id ON subjects(department_id);
CREATE TRIGGER trg_update_subjects_updated_at
    BEFORE UPDATE ON subjects FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


CREATE TABLE cohorts (
                         id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         code       VARCHAR(50)  NOT NULL UNIQUE,
                         name       VARCHAR(255) NOT NULL,
                         start_year INT NOT NULL,
                         end_year   INT NOT NULL,
                         active     BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE TRIGGER trg_update_cohorts_updated_at
    BEFORE UPDATE ON cohorts FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


CREATE TABLE student_classes (
                                 id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 created_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 updated_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 code               VARCHAR(50)  NOT NULL,
                                 name               VARCHAR(255) NOT NULL,
                                 department_id      BIGINT,
                                 cohort_id          BIGINT,
                                 intake_year        INTEGER,
                                 program            VARCHAR(255),
                                 advisor_teacher_id BIGINT,
                                 active             BOOLEAN NOT NULL DEFAULT TRUE,
                                 CONSTRAINT uk_student_classes_code UNIQUE (code),
                                 CONSTRAINT fk_student_classes_department      FOREIGN KEY (department_id)      REFERENCES departments(id)  ON DELETE SET NULL,
                                 CONSTRAINT fk_student_classes_cohort          FOREIGN KEY (cohort_id)          REFERENCES cohorts(id),
                                 CONSTRAINT fk_student_classes_advisor_teacher FOREIGN KEY (advisor_teacher_id) REFERENCES teachers(id)
);
CREATE INDEX idx_student_classes_code               ON student_classes(code);
CREATE INDEX idx_student_classes_department_id      ON student_classes(department_id);
CREATE INDEX idx_student_classes_intake_year        ON student_classes(intake_year);
CREATE INDEX idx_student_classes_active             ON student_classes(active);
CREATE INDEX idx_student_classes_advisor_teacher_id ON student_classes(advisor_teacher_id);
CREATE TRIGGER trg_update_student_classes_updated_at
    BEFORE UPDATE ON student_classes FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


CREATE TABLE students (
                          id               BIGSERIAL PRIMARY KEY,
                          user_id          BIGINT NOT NULL UNIQUE,
                          student_code     VARCHAR(50) NOT NULL UNIQUE,
                          department_id    BIGINT,
                          student_class_id BIGINT,
                          phone            VARCHAR(20),
                          active           BOOLEAN NOT NULL DEFAULT TRUE,
                          created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          updated_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          FOREIGN KEY (user_id)          REFERENCES users(id)          ON DELETE CASCADE,
                          FOREIGN KEY (department_id)    REFERENCES departments(id)    ON DELETE SET NULL,
                          FOREIGN KEY (student_class_id) REFERENCES student_classes(id) ON DELETE SET NULL
);
CREATE INDEX idx_students_user_id          ON students(user_id);
CREATE INDEX idx_students_student_code     ON students(student_code);
CREATE INDEX idx_students_department_id    ON students(department_id);
CREATE INDEX idx_students_student_class_id ON students(student_class_id);
CREATE INDEX idx_students_active           ON students(active);
CREATE TRIGGER trg_update_students_updated_at
    BEFORE UPDATE ON students FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


-- ============================================================
-- PHẦN 2: LỚP HỌC PHẦN (SECTIONS)
-- ============================================================

CREATE TABLE sections (
                          id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          created_at             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          updated_at             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          active                 BOOLEAN NOT NULL DEFAULT TRUE,
                          code                   VARCHAR(255) NOT NULL,
                          name                   VARCHAR(255) NOT NULL,
                          current_students       INTEGER NOT NULL DEFAULT 0,
                          max_students           INTEGER NOT NULL DEFAULT 30,
                          min_students           INTEGER NOT NULL DEFAULT 0,
                          semester_id            BIGINT,
                          subject_id             BIGINT,
                          teacher_id             BIGINT,
                          status                 VARCHAR(20) NOT NULL DEFAULT 'OPEN',
                          canceled_at            TIMESTAMP NULL,
                          canceled_reason        TEXT NULL,
                          merged_into_section_id BIGINT NULL,
                          registration_enabled   BOOLEAN NOT NULL DEFAULT TRUE,
                          enrollment_start_date  DATE,
                          enrollment_end_date    DATE,
                          CONSTRAINT uk_sections_code UNIQUE (code),
                          CONSTRAINT chk_sections_lifecycle_status CHECK (status IN ('OPEN','CLOSED','CANCELED','MERGED')),
                          CONSTRAINT fk_sections_semester    FOREIGN KEY (semester_id)            REFERENCES semesters(id) ON DELETE SET NULL,
                          CONSTRAINT fk_sections_subject     FOREIGN KEY (subject_id)             REFERENCES subjects(id)  ON DELETE SET NULL,
                          CONSTRAINT fk_sections_teacher     FOREIGN KEY (teacher_id)             REFERENCES users(id)     ON DELETE SET NULL,
                          CONSTRAINT fk_sections_merged_into FOREIGN KEY (merged_into_section_id) REFERENCES sections(id)  ON DELETE SET NULL
);
CREATE INDEX idx_sections_code        ON sections(code);
CREATE INDEX idx_sections_semester_id ON sections(semester_id);
CREATE INDEX idx_sections_subject_id  ON sections(subject_id);
CREATE INDEX idx_sections_teacher_id  ON sections(teacher_id);
CREATE INDEX idx_sections_status      ON sections(status);
CREATE INDEX idx_sections_active      ON sections(active);
CREATE TRIGGER trg_update_sections_updated_at
    BEFORE UPDATE ON sections FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


CREATE TABLE section_time_slots (
                                    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                    section_id  BIGINT NOT NULL,
                                    day_of_week SMALLINT NOT NULL,
                                    start_time  TIME NOT NULL,
                                    end_time    TIME NOT NULL,
                                    room        VARCHAR(50),   -- V23
                                    CONSTRAINT fk_section_time_slots_section FOREIGN KEY (section_id) REFERENCES sections(id) ON DELETE CASCADE
);
CREATE INDEX idx_section_time_slots_section_id ON section_time_slots(section_id);
CREATE TRIGGER trg_update_section_time_slots_updated_at
    BEFORE UPDATE ON section_time_slots FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


CREATE TABLE enrollments (
                             id                            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             created_at                    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             updated_at                    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             section_id                    BIGINT NOT NULL,
                             student_id                    BIGINT NOT NULL,
                             status                        VARCHAR(50),
                             process_score                 NUMERIC(4,2),
                             exam_score                    NUMERIC(4,2),
                             final_score                   NUMERIC(4,2),
                             scored_at                     TIMESTAMP,
                             score_locked                  BOOLEAN NOT NULL DEFAULT FALSE,
                             score_overridden              BOOLEAN NOT NULL DEFAULT FALSE,
                             score_override_reason         TEXT,
                             score_overridden_at           TIMESTAMP,
                             process_score_before_override NUMERIC(4,2),
                             exam_score_before_override    NUMERIC(4,2),
                             final_score_before_override   NUMERIC(4,2),
                             CONSTRAINT uk_enrollments_section_student UNIQUE (section_id, student_id),
                             CONSTRAINT fk_enrollments_section FOREIGN KEY (section_id) REFERENCES sections(id) ON DELETE CASCADE,
                             CONSTRAINT fk_enrollments_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
);
CREATE INDEX idx_enrollments_section_id ON enrollments(section_id);
CREATE INDEX idx_enrollments_student_id ON enrollments(student_id);
CREATE INDEX idx_enrollments_status     ON enrollments(status);
CREATE TRIGGER trg_update_enrollments_updated_at
    BEFORE UPDATE ON enrollments FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


-- ============================================================
-- PHẦN 3: RBAC
-- ============================================================

CREATE TABLE roles (
                       id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       name        VARCHAR(100) NOT NULL,
                       description VARCHAR(255),
                       CONSTRAINT uk_roles_name UNIQUE (name)
);
CREATE TRIGGER trg_update_roles_updated_at
    BEFORE UPDATE ON roles FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


CREATE TABLE permissions (
                             id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             name        VARCHAR(100) NOT NULL,
                             resource    VARCHAR(100) NOT NULL,
                             action      VARCHAR(100) NOT NULL,
                             description VARCHAR(255),
                             CONSTRAINT uk_permissions_name UNIQUE (name)
);
CREATE TRIGGER trg_update_permissions_updated_at
    BEFORE UPDATE ON permissions FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


CREATE TABLE role_permissions (
                                  role_id       BIGINT NOT NULL,
                                  permission_id BIGINT NOT NULL,
                                  PRIMARY KEY (role_id, permission_id),
                                  FOREIGN KEY (role_id)       REFERENCES roles(id)       ON DELETE CASCADE,
                                  FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE
);


CREATE TABLE user_roles (
                            user_id BIGINT NOT NULL,
                            role_id BIGINT NOT NULL,
                            PRIMARY KEY (user_id, role_id),
                            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
                            FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);


-- ============================================================
-- PHẦN 4: CHƯƠNG TRÌNH ĐÀO TẠO (V24)
-- ============================================================

CREATE TABLE academic_programs (
                                   id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                   updated_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                   code          VARCHAR(50)  NOT NULL UNIQUE,
                                   name          VARCHAR(255) NOT NULL,
                                   department_id BIGINT,
                                   total_credits INTEGER NOT NULL DEFAULT 120,
                                   description   TEXT,
                                   active        BOOLEAN NOT NULL DEFAULT TRUE,
                                   FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE SET NULL
);
CREATE TRIGGER trg_update_academic_programs_updated_at
    BEFORE UPDATE ON academic_programs FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


CREATE TABLE program_subjects (
                                  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  program_id   BIGINT NOT NULL,
                                  subject_id   BIGINT NOT NULL,
                                  semester     INTEGER NOT NULL DEFAULT 1,
                                  subject_type VARCHAR(50) NOT NULL DEFAULT 'COMPULSORY',
                                  pass_score   NUMERIC(4,2) NOT NULL DEFAULT 5.0,
                                  CONSTRAINT uk_program_subjects UNIQUE (program_id, subject_id),
                                  FOREIGN KEY (program_id) REFERENCES academic_programs(id) ON DELETE CASCADE,
                                  FOREIGN KEY (subject_id) REFERENCES subjects(id)          ON DELETE CASCADE
);


-- FK student_classes → academic_programs (V24)
ALTER TABLE student_classes
    ADD COLUMN academic_program_id BIGINT,
    ADD CONSTRAINT fk_student_classes_academic_program
        FOREIGN KEY (academic_program_id) REFERENCES academic_programs(id) ON DELETE SET NULL;


-- ============================================================
-- PHẦN 5: SEED DATA RBAC (V19 + V20)
-- Roles, Permissions, và mapping — KHÔNG có CLASS:* (đã remove ở V20)
-- ============================================================

INSERT INTO roles (name, description) VALUES
                                          ('ROLE_ADMIN',   'Quản trị viên hệ thống'),
                                          ('ROLE_TEACHER', 'Giảng viên'),
                                          ('ROLE_STUDENT', 'Sinh viên');

INSERT INTO permissions (name, resource, action, description) VALUES
                                                                  -- DEPARTMENT
                                                                  ('DEPARTMENT:CREATE', 'DEPARTMENT', 'CREATE', 'Tạo khoa/bộ môn'),
                                                                  ('DEPARTMENT:READ',   'DEPARTMENT', 'READ',   'Xem khoa/bộ môn'),
                                                                  ('DEPARTMENT:UPDATE', 'DEPARTMENT', 'UPDATE', 'Cập nhật khoa/bộ môn'),
                                                                  ('DEPARTMENT:DELETE', 'DEPARTMENT', 'DELETE', 'Xóa khoa/bộ môn'),
                                                                  -- SUBJECT
                                                                  ('SUBJECT:CREATE', 'SUBJECT', 'CREATE', 'Tạo môn học'),
                                                                  ('SUBJECT:READ',   'SUBJECT', 'READ',   'Xem môn học'),
                                                                  ('SUBJECT:UPDATE', 'SUBJECT', 'UPDATE', 'Cập nhật môn học'),
                                                                  ('SUBJECT:DELETE', 'SUBJECT', 'DELETE', 'Xóa môn học'),
                                                                  -- SEMESTER
                                                                  ('SEMESTER:CREATE', 'SEMESTER', 'CREATE', 'Tạo học kỳ'),
                                                                  ('SEMESTER:READ',   'SEMESTER', 'READ',   'Xem học kỳ'),
                                                                  ('SEMESTER:UPDATE', 'SEMESTER', 'UPDATE', 'Cập nhật học kỳ'),
                                                                  ('SEMESTER:DELETE', 'SEMESTER', 'DELETE', 'Xóa học kỳ'),
                                                                  -- COHORT (niên khóa)
                                                                  ('COHORT:CREATE', 'COHORT', 'CREATE', 'Tạo niên khóa'),
                                                                  ('COHORT:READ',   'COHORT', 'READ',   'Xem niên khóa'),
                                                                  ('COHORT:UPDATE', 'COHORT', 'UPDATE', 'Cập nhật niên khóa'),
                                                                  ('COHORT:DELETE', 'COHORT', 'DELETE', 'Xóa niên khóa'),
                                                                  -- SECTION (lớp học phần)
                                                                  ('SECTION:CREATE', 'SECTION', 'CREATE', 'Tạo lớp học phần'),
                                                                  ('SECTION:READ',   'SECTION', 'READ',   'Xem lớp học phần'),
                                                                  ('SECTION:UPDATE', 'SECTION', 'UPDATE', 'Cập nhật lớp học phần'),
                                                                  ('SECTION:DELETE', 'SECTION', 'DELETE', 'Xóa lớp học phần'),
                                                                  -- TEACHER
                                                                  ('TEACHER:CREATE', 'TEACHER', 'CREATE', 'Tạo hồ sơ giảng viên'),
                                                                  ('TEACHER:READ',   'TEACHER', 'READ',   'Xem hồ sơ giảng viên'),
                                                                  ('TEACHER:UPDATE', 'TEACHER', 'UPDATE', 'Cập nhật hồ sơ giảng viên'),
                                                                  ('TEACHER:DELETE', 'TEACHER', 'DELETE', 'Xóa hồ sơ giảng viên'),
                                                                  -- STUDENT
                                                                  ('STUDENT:CREATE', 'STUDENT', 'CREATE', 'Tạo hồ sơ sinh viên'),
                                                                  ('STUDENT:READ',   'STUDENT', 'READ',   'Xem hồ sơ sinh viên'),
                                                                  ('STUDENT:UPDATE', 'STUDENT', 'UPDATE', 'Cập nhật hồ sơ sinh viên'),
                                                                  ('STUDENT:DELETE', 'STUDENT', 'DELETE', 'Xóa hồ sơ sinh viên'),
                                                                  -- STUDENT_CLASS (lớp hành chính)
                                                                  ('STUDENT_CLASS:CREATE', 'STUDENT_CLASS', 'CREATE', 'Tạo lớp hành chính'),
                                                                  ('STUDENT_CLASS:READ',   'STUDENT_CLASS', 'READ',   'Xem lớp hành chính'),
                                                                  ('STUDENT_CLASS:UPDATE', 'STUDENT_CLASS', 'UPDATE', 'Cập nhật lớp hành chính'),
                                                                  ('STUDENT_CLASS:DELETE', 'STUDENT_CLASS', 'DELETE', 'Xóa lớp hành chính'),
                                                                  -- ENROLLMENT
                                                                  ('ENROLLMENT:CREATE', 'ENROLLMENT', 'CREATE', 'Đăng ký học phần'),
                                                                  ('ENROLLMENT:READ',   'ENROLLMENT', 'READ',   'Xem đăng ký học phần'),
                                                                  ('ENROLLMENT:UPDATE', 'ENROLLMENT', 'UPDATE', 'Cập nhật đăng ký học phần'),
                                                                  ('ENROLLMENT:DELETE', 'ENROLLMENT', 'DELETE', 'Hủy đăng ký học phần'),
                                                                  -- USER
                                                                  ('USER:CREATE', 'USER', 'CREATE', 'Tạo tài khoản'),
                                                                  ('USER:READ',   'USER', 'READ',   'Xem tài khoản'),
                                                                  ('USER:UPDATE', 'USER', 'UPDATE', 'Cập nhật tài khoản'),
                                                                  ('USER:DELETE', 'USER', 'DELETE', 'Xóa tài khoản');


-- ROLE_ADMIN: toàn quyền
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r, permissions p
WHERE r.name = 'ROLE_ADMIN';


-- ROLE_TEACHER
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
         JOIN permissions p ON p.name IN (
                                          'DEPARTMENT:READ',
                                          'SUBJECT:READ',
                                          'SEMESTER:READ',
                                          'COHORT:READ',
                                          'SECTION:READ',
                                          'TEACHER:READ', 'TEACHER:UPDATE',
                                          'STUDENT:READ',
                                          'STUDENT_CLASS:READ',
                                          'ENROLLMENT:READ', 'ENROLLMENT:UPDATE',
                                          'USER:READ'
    )
WHERE r.name = 'ROLE_TEACHER';


-- ROLE_STUDENT
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
         JOIN permissions p ON p.name IN (
                                          'DEPARTMENT:READ',
                                          'SUBJECT:READ',
                                          'SEMESTER:READ',
                                          'SECTION:READ',
                                          'TEACHER:READ',
                                          'STUDENT:READ', 'STUDENT:UPDATE',
                                          'STUDENT_CLASS:READ',
                                          'ENROLLMENT:CREATE', 'ENROLLMENT:READ', 'ENROLLMENT:DELETE',
                                          'USER:READ', 'USER:UPDATE'
    )
WHERE r.name = 'ROLE_STUDENT';


-- ============================================================
-- PHẦN 6: VIEW
-- ============================================================

CREATE OR REPLACE VIEW v_sections_with_teacher AS
SELECT
    s.id              AS section_id,
    s.code            AS section_code,
    s.name            AS section_name,
    s.semester_id,
    s.subject_id,
    s.current_students,
    s.max_students,
    subj.name         AS subject_name,
    sem.name          AS semester_name,
    t.id              AS teacher_id,
    t.user_id         AS teacher_user_id,
    u.username        AS teacher_username,
    u.email           AS teacher_email,
    t.employee_code,
    d.code            AS department_code,
    d.name            AS department_name
FROM sections s
         LEFT JOIN subjects    subj ON s.subject_id  = subj.id
         LEFT JOIN semesters   sem  ON s.semester_id = sem.id
         LEFT JOIN teachers    t    ON s.teacher_id  = t.user_id
         LEFT JOIN users       u    ON t.user_id     = u.id
         LEFT JOIN departments d    ON t.department_id = d.id;