-- =====================================================
-- Migration V2: Authentication & Authorization System (UPDATED)
-- =====================================================
-- Version: 2.0 (Compatible with V1 syntax)
-- Mục đích: Thêm hệ thống RBAC và Token Management
-- Changes: Updated PRIMARY KEY syntax để match V1
-- =====================================================

-- =====================================================
-- 1. ROLES TABLE
-- =====================================================
CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_roles_name ON roles(name);

-- =====================================================
-- 2. PERMISSIONS TABLE
-- =====================================================
CREATE TABLE permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    resource VARCHAR(50) NOT NULL,
    action VARCHAR(50) NOT NULL,
    description VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_permissions_resource_action ON permissions(resource, action);

-- =====================================================
-- 3. ROLE_PERMISSIONS TABLE (Many-to-Many)
-- =====================================================
CREATE TABLE role_permissions (
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    granted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permissions_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
    CONSTRAINT fk_role_permissions_permission FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE
);

-- =====================================================
-- 4. USER_ROLES TABLE (Many-to-Many)
-- =====================================================
CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

CREATE INDEX idx_user_roles_user_id ON user_roles(user_id);

-- =====================================================
-- 5. REFRESH_TOKENS TABLE
-- =====================================================
CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(255) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    revoked_at TIMESTAMP,
    replaced_by_token VARCHAR(255),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_refresh_tokens_token ON refresh_tokens(token);
CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens(user_id);
CREATE INDEX idx_refresh_tokens_expires_at ON refresh_tokens(expires_at);

-- =====================================================
-- 6. PASSWORD_RESET_TOKENS TABLE
-- =====================================================
CREATE TABLE password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(255) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    used_at TIMESTAMP,
    CONSTRAINT fk_password_reset_tokens_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_password_reset_tokens_token ON password_reset_tokens(token);
CREATE INDEX idx_password_reset_tokens_user_id ON password_reset_tokens(user_id);
CREATE INDEX idx_password_reset_tokens_expires_at ON password_reset_tokens(expires_at);

-- =====================================================
-- 7. SEED DATA - Default Roles
-- =====================================================
INSERT INTO roles (id, name, description, created_at, updated_at) VALUES
    (1, 'ROLE_ADMIN', 'Administrator - Full system access', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, 'ROLE_TEACHER', 'Teacher - Can manage courses and students', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (3, 'ROLE_STUDENT', 'Student - Can enroll and learn', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Reset sequence
SELECT setval('roles_id_seq', (SELECT MAX(id) FROM roles), true);

-- =====================================================
-- 8. SEED DATA - Basic Permissions
-- =====================================================
-- Course permissions
INSERT INTO permissions (name, resource, action, description, created_at, updated_at) VALUES
    ('COURSE:CREATE', 'COURSE', 'CREATE', 'Create new course', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('COURSE:READ', 'COURSE', 'READ', 'View course details', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('COURSE:UPDATE', 'COURSE', 'UPDATE', 'Update course', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('COURSE:DELETE', 'COURSE', 'DELETE', 'Delete course', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('COURSE:PUBLISH', 'COURSE', 'PUBLISH', 'Publish course', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- User permissions
INSERT INTO permissions (name, resource, action, description, created_at, updated_at) VALUES
    ('USER:CREATE', 'USER', 'CREATE', 'Create new iam', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('USER:READ', 'USER', 'READ', 'View iam details', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('USER:UPDATE', 'USER', 'UPDATE', 'Update iam', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('USER:DELETE', 'USER', 'DELETE', 'Delete iam', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Enrollment permissions
INSERT INTO permissions (name, resource, action, description, created_at, updated_at) VALUES
    ('ENROLLMENT:CREATE', 'ENROLLMENT', 'CREATE', 'Enroll student', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ENROLLMENT:READ', 'ENROLLMENT', 'READ', 'View enrollment', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ENROLLMENT:UPDATE', 'ENROLLMENT', 'UPDATE', 'Update enrollment', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ENROLLMENT:DELETE', 'ENROLLMENT', 'DELETE', 'Cancel enrollment', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- =====================================================
-- 9. SEED DATA - Role-Permission Mapping
-- =====================================================
-- ADMIN có tất cả quyền
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
CROSS JOIN permissions p
WHERE r.name = 'ROLE_ADMIN';

-- TEACHER có quyền quản lý course và xem iam
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r, permissions p
WHERE r.name = 'ROLE_TEACHER'
  AND (
      p.resource = 'COURSE'
      OR (p.resource = 'USER' AND p.action = 'READ')
      OR p.resource = 'ENROLLMENT'
  );

-- STUDENT chỉ có quyền READ và ENROLL
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r, permissions p
WHERE r.name = 'ROLE_STUDENT'
  AND (
      (p.resource = 'COURSE' AND p.action = 'READ')
      OR (p.resource = 'ENROLLMENT' AND p.action IN ('CREATE', 'READ'))
  );

-- =====================================================
-- 10. MIGRATE EXISTING USERS TO NEW RBAC SYSTEM
-- =====================================================
-- Map existing users (có role column trong users table) sang user_roles table

-- Admin users
INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id
FROM users u
CROSS JOIN roles r
WHERE u.role = 'ROLE_ADMIN'
  AND r.name = 'ROLE_ADMIN'
ON CONFLICT DO NOTHING;

-- Teacher users
INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id
FROM users u
CROSS JOIN roles r
WHERE u.role = 'ROLE_TEACHER'
  AND r.name = 'ROLE_TEACHER'
ON CONFLICT DO NOTHING;

-- Student users
INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id
FROM users u
CROSS JOIN roles r
WHERE u.role = 'ROLE_STUDENT'
  AND r.name = 'ROLE_STUDENT'
ON CONFLICT DO NOTHING;

-- =====================================================
-- 11. ADD TRIGGERS FOR AUTO-UPDATE TIMESTAMPS
-- =====================================================
-- Apply updated_at trigger cho các bảng mới

CREATE TRIGGER trg_update_roles_updated_at
    BEFORE UPDATE ON roles
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_update_permissions_updated_at
    BEFORE UPDATE ON permissions
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_update_refresh_tokens_updated_at
    BEFORE UPDATE ON refresh_tokens
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_update_password_reset_tokens_updated_at
    BEFORE UPDATE ON password_reset_tokens
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- =====================================================
-- 12. VALIDATION
-- =====================================================
DO $$
DECLARE
    roles_count INTEGER;
    permissions_count INTEGER;
    user_roles_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO roles_count FROM roles;
    SELECT COUNT(*) INTO permissions_count FROM permissions;
    SELECT COUNT(*) INTO user_roles_count FROM user_roles;
    
    IF roles_count != 3 THEN
        RAISE EXCEPTION 'Expected 3 roles, found %', roles_count;
    END IF;
    
    IF permissions_count != 13 THEN
        RAISE EXCEPTION 'Expected 13 permissions, found %', permissions_count;
    END IF;
    
    IF user_roles_count < 3 THEN
        RAISE EXCEPTION 'Expected at least 3 user_roles (from existing users), found %', user_roles_count;
    END IF;
    
    RAISE NOTICE 'V2 Migration SUCCESS: % roles, % permissions, % user_roles',
        roles_count, permissions_count, user_roles_count;
END $$;
