-- ============================================================
-- V5: Administrative classes + grading components
-- - Add admin_classes (lớp hành chính)
-- - Link students to admin_class
-- - Add subject grading weights (process/exam)
-- - Expand enrollments to store component scores + locking + override markers
-- ============================================================

-- 1) Administrative classes (lớp hành chính)
CREATE TABLE IF NOT EXISTS admin_classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    department_id BIGINT,
    intake_year INTEGER,
    program VARCHAR(255),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_admin_classes_code UNIQUE (code),
    CONSTRAINT fk_admin_classes_department FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_admin_classes_code ON admin_classes(code);
CREATE INDEX IF NOT EXISTS idx_admin_classes_department_id ON admin_classes(department_id);
CREATE INDEX IF NOT EXISTS idx_admin_classes_intake_year ON admin_classes(intake_year);
CREATE INDEX IF NOT EXISTS idx_admin_classes_active ON admin_classes(active);

ALTER TABLE students
    ADD COLUMN IF NOT EXISTS admin_class_id BIGINT;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_students_admin_class'
    ) THEN
        ALTER TABLE students
            ADD CONSTRAINT fk_students_admin_class
            FOREIGN KEY (admin_class_id) REFERENCES admin_classes(id) ON DELETE SET NULL;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_students_admin_class_id ON students(admin_class_id);

-- 2) Subject grading weights (tỷ lệ điểm)
ALTER TABLE subjects
    ADD COLUMN IF NOT EXISTS process_weight SMALLINT NOT NULL DEFAULT 40,
    ADD COLUMN IF NOT EXISTS exam_weight SMALLINT NOT NULL DEFAULT 60;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'chk_subjects_grade_weights'
    ) THEN
        ALTER TABLE subjects
            ADD CONSTRAINT chk_subjects_grade_weights
            CHECK (
                process_weight BETWEEN 0 AND 100
                AND exam_weight BETWEEN 0 AND 100
                AND (process_weight + exam_weight = 100)
            );
    END IF;
END $$;

-- 3) Enrollment grading components + locking + override markers
ALTER TABLE enrollments
    ADD COLUMN IF NOT EXISTS process_score NUMERIC(4,2),
    ADD COLUMN IF NOT EXISTS exam_score NUMERIC(4,2),
    ADD COLUMN IF NOT EXISTS final_score NUMERIC(4,2),
    ADD COLUMN IF NOT EXISTS scored_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS score_locked BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS score_overridden BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS score_override_reason TEXT,
    ADD COLUMN IF NOT EXISTS score_overridden_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS process_score_before_override NUMERIC(4,2),
    ADD COLUMN IF NOT EXISTS exam_score_before_override NUMERIC(4,2),
    ADD COLUMN IF NOT EXISTS final_score_before_override NUMERIC(4,2);

